config/routes.rb
Rails.application.routes.draw do
  get 'entries/index'

    resources :entries do
      resources :comments
    end

  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @entry = Entry.find(params[:entry_id])
    @comment = @entry.comments.create(comments_params)

    redirect_to entry_path(@entry)
  end

  def destroy
    @entry = Entry.find(params[:entry_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to entry_path(@entry)
  end

  private
    def comments_params
      params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(required_params)
    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(required_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private
    def required_params
      params.require(:entry).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/comments/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <%= link_to 'Delete', [comment.entry, comment], method: :delete %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@entry, @entry.comments.build]) do |f| %>
<p>
<%= f.label :author_name %>
<%= f.text_field :author_name %>
</p>
<p>
<%= f.label :body %>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>

<% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %> prohibited
        this entry from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :text %> <br>
  <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/entries/edit.html.erb
<h2>Edit Entry</h2>

<%= render 'form' %>
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>My Entries</h1>
<%= link_to 'New Entry', new_entry_path %>
<% @entries.each do |entry| %>
  <ul>
    <li><%= entry.title %> | <%= link_to 'Go', entry_path(entry) %> <%= link_to 'Edit', edit_entry_path(entry) %> <%= link_to 'Delete', entry_path(entry), method: :delete, data: {confirm: 'Are you sure you want to delete this entry?'} %></li>
  </ul>
<% end %>

app/views/entries/new.html.erb
<h2>New Entry</h2>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p><strong>Title: <%= @entry.title %></strong></p>
<p><%= @entry.text %></p>

<%= render @entry.comments %>

<h4>Add Comments</h4>
<%= render 'comments/form' %>

<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>